GRANT READ, WRITE ON DIRECTORY external_geo_tables TO bl_cl_1st;
GRANT READ, WRITE ON DIRECTORY external_cust_tables TO bl_cl_1st;
GRANT READ, WRITE ON DIRECTORY external_emp_tables TO bl_cl_1st;
GRANT READ, WRITE ON DIRECTORY external_ext_tables TO bl_cl_1st;
GRANT READ, WRITE ON DIRECTORY external_prod_tables TO bl_cl_1st;
GRANT SELECT ON sa_src.ext_countries TO bl_cl_1st;
GRANT SELECT ON sa_src.ext_structures TO bl_cl_1st;
GRANT SELECT ON sa_src.ext_full_data TO bl_cl_1st;
GRANT SELECT ON sa_src.ext_bra_sizes TO bl_cl_1st;
GRANT SELECT ON sa_src.ext_panty_sizes TO bl_cl_1st;
GRANT SELECT ON sa_src.ext_customers TO bl_cl_1st;
GRANT SELECT ON sa_src.ext_employees TO bl_cl_1st;
GRANT SELECT ON sa_src.ext_stores TO bl_cl_1st;
GRANT SELECT ON sa_src.ext_payment_methods TO bl_cl_1st;
GRANT SELECT ON sa_src.ext_products TO bl_cl_1st;
