--------------------------------------------------------
--  File created - Saturday-December-02-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "DATA_MART"."SALES" 
   (	"YEAR_MONTH" VARCHAR2(11 BYTE), 
	"POSITION_GRADE" VARCHAR2(50 BYTE), 
	"REGION" VARCHAR2(100 BYTE), 
	"MAX_SALES$" VARCHAR2(40 BYTE), 
	"MIN_SALES$" VARCHAR2(40 BYTE), 
	"SALES$" VARCHAR2(21 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PDB_DWH" ;
SET DEFINE OFF;
